title: Mangesh Damre # your name (or website title) here
![Jetpacktocat](https://octodex.github.com/images/jetpacktocat.png)
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  PostDoctoral Fellow<br>
  02/2019-Continued...<br>
  Computational Chemistry,<br>
  University of Cincinnati, OH
  <br><br>
  <a href="/pdf/Mangesh_Damre_Resume.pdf" target="_blank">My Resume</a><br>
  <br><br>
  <a href="https://www.linkedin.com/in/mangesh-damre/" target="_blank">View My LinkedIn Profile</a><br>
  <a href="https://orcid.org/0000-0002-4371-3815/" target="_blank">View My ORCID Profile</a><br>
  <a href="https://www.researchgate.net/profile/Mangesh_Damre" target="_blank">View My ResearchGate Profile</a>
theme: jekyll-theme-minimal
