title: Mangesh Damre # your name (or website title) here
logo: "/images/Screenshot from 2021-01-12 09-24-16.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Highly motivated Postdoctoral Researcher conducts Computational Chemistry research and participates in brainstorming
topics that demonstrate experience with complex data analysis and high-performance computing. Dedicated, versatile computational chemist, author and co-author of international
publications in peer-reviewed journals with extensive research experience in molecular modeling. Recent PhD in Neurobiology (Computational) with effective verbal and written communication skills to deliver excellent presentations and prepare written reports. Broad range of knowledge in advanced
computational techniques. Develop and apply computational methods in the fields of biophysics, chemistry and other computationally intensive areas. Optimize and parallelize scientific
programs for conventional clusters, supercomputers and GPU accelerated computers. Solve challenging problems in computational biophysics/ chemistry field through varied skills and
interdisciplinary science knowledge.<br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/mangesh-damre/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
